### ISSUE TITLE
Data visualization

### ISSUE THREAD

**Issue by deepai-lab** [VSainteuf/pastis-benchmark#11]
Hi, May I know how to visualize multi-spectral image (cube)? The code shows to visualize RGB images, however, if I want to show multi-band, how can I do that? Thanks in advance.

**Comment by VSainteuf** [comment]
Hi @deepai-lab,
I guess you mainly have two options:
- If you are interested in one specific multispectral band, say B08, you can plot (B08,G,B) instead of (R,G,B)
- Otherwise you'll have to resort to a dimension reduction technique, e.g., applying PCA in the 10-dimensional spectral space and taking plotting the 3 principal components.

**Comment by deepai-lab** [comment]
Thank you.
